platform :ios, '5.0'

pod 'DCIntrospect'
pod 'GHUnitIOS'
pod 'BlocksKit'
pod 'Underscore.m'
pod 'AQGridView'
pod 'JASidePanels'
pod 'QuickDialog'
pod 'OCCalendar'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'Reachability'
#pod 'AFNetworking'
pod 'AFNetworking', '1.3.1'
pod 'MagicalRecord'
pod 'NoticeView'
pod 'ELCImagePickerController', '0.1.3'

pod 'LUKeychainAccess'
pod 'JASidePanels', '~> 1.3.2'
